#!/bin/bash

export HEAP_SIZE=2048m
export JAVA_OPTS="-Xmx$HEAP_SIZE"

rm -rf generatedCache

echo Set classpath...
export CLASSPATH=$CLASSPATH:$DELITE/dsls/sac-staged/target/$VANILLA_VERSION/classes/:$DELITE/framework/target/$VANILLA_VERSION/classes:$LMS/target/$VANILLA_VERSION/classes:.
echo Stage...
$SCALA_VIRTUALIZED/scala -Ddelite.home.dir=$DELITE epfl.mdarrays.tests.gol.GameOfLifeStagedRunner

echo Execute...
java -Xmx$HEAP_SIZE -cp $DELITE/runtime/target/$VANILLA_VERSION/classes:$SCALA_VANILLA/../lib/scala-library.jar:$SCALA_VANILLA/../lib/scala-compiler.jar -Ddelite.threads=1 -Ddelite.runs=10 ppl.delite.runtime.Delite out.deg
echo Execute...
java -Xmx$HEAP_SIZE -cp $DELITE/runtime/target/$VANILLA_VERSION/classes:$SCALA_VANILLA/../lib/scala-library.jar:$SCALA_VANILLA/../lib/scala-compiler.jar -Ddelite.threads=2 -Ddelite.runs=10 ppl.delite.runtime.Delite out.deg
