#!/bin/bash
while `true`
do

read size
if [ "$size" == "" ] 
then 
    exit
fi
size=`echo $size | cut -d ' ' -f 3`

a0=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a1=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a2=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a3=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a4=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a5=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a6=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a7=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a8=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a9=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`

jit_block=`echo "scale=10; ( $a5 + $a6 + $a7 + $a8 + $a9 ) / 5 " | bc`

a0=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a1=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a2=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a3=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a4=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a5=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a6=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a7=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a8=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a9=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`

jit_noblock=`echo "scale=10; ( $a5 + $a6 + $a7 + $a8 + $a9 ) / 5 " | bc`

a0=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a1=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a2=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a3=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a4=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a5=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a6=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a7=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a8=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`
a9=`read tmp; echo $tmp | cut -d ' ' -f 7 | tr -d 's'`

nojit=`echo "scale=10; ( $a5 + $a6 + $a7 + $a8 + $a9 ) / 5 " | bc`

echo -e "$size\t$jit_block\t$jit_noblock\t$nojit"

done
